# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant::Config.run do |config|
  ### Troubleshooting Options ###
  
  # Enable for console access in Virtualbox
  #config.vm.boot_mode = :gui
  
  ### Main ###    
  # Setup the box - using a publicly maintained base box
  config.vm.box_url = "http://files.vagrantup.com/precise64.box"
  config.vm.box = "precise64.box"
  
  # SSH - Forward 22 to 2222
  config.vm.forward_port 22, 2222
  # XRDP - Forward 3389 to 33389
  config.vm.forward_port 3389, 33389
  
  # Apply cookbooks
  config.vm.provision :chef_solo do |chef|
	chef.cookbooks_path = "cookbooks"
	chef.add_recipe("boilerplate")
	chef.add_recipe("xrdp")
	end 
end