# -*- mode: ruby -*-
# vi: set ft=ruby :
# Basic development VM with super minimal desktop support
#
# -  Installs xmonad as a tiling manager
# -  Mininmal development tools


Vagrant::Config.run do |config|
  
  # Enable for console access in Virtualbox
  config.vm.boot_mode = :gui
  
  ### Main ###    
  # Setup the box - using a publicly maintained base box
  config.vm.box_url = "https://dl.dropboxusercontent.com/u/13054557/vagrant_boxes/debian-squeeze.box"
  config.vm.box = "debian-squeeze.box"
  
  # SSH - Forward 22 to 2222
  config.vm.forward_port 22, 2222

	# System memory
	config.vm.customize ["modifyvm", :id, "--memory", 2048]
	
	# Video memory
	config.vm.customize ["modifyvm", :id, "--vram", 128]
	
	# Enable 3d accel
	config.vm.customize ["modifyvm", :id, "--accelerate3d", "on"]
	
  # Apply cookbooks
  config.vm.provision :puppet do |puppet|
	puppet.manifests_path = "manifests"

	end 
end