# -*- mode: ruby -*-
# vi: set ft=ruby :



Vagrant::Config.run do |config|
  
  # Enable for console access in Virtualbox
  #config.vm.boot_mode = :gui
  
  ### Main ###    
  # Setup the box - using a publicly maintained base box
  config.vm.box_url = "https://dl.dropboxusercontent.com/u/547671/thinkstack-raring64.box"
  config.vm.box = "ubuntu-13.04.box"
  
  # SSH - Forward 22 to 2222
  config.vm.forward_port 22, 2223

  # System memory
  config.vm.customize ["modifyvm", :id, "--memory", 2048]
  
  # Video memory
  config.vm.customize ["modifyvm", :id, "--vram", 128]
  
  # Enable 3d accel
  config.vm.customize ["modifyvm", :id, "--accelerate3d", "on"]
  
  # Disable COM port
  config.vm.customize ["modifyvm", :id, "--uart1", "off"]
  
  # Enabled shared clipboard
  config.vm.customize ["modifyvm", :id, "--clipboard", "bidirectional"]

end
