# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant::Config.run do |config|
  ### Troubleshooting Options ###
  
  # Enable for console access in Virtualbox
  #config.vm.boot_mode = :gui
  
  ### Main ###    
  # Setup the box - using a publicly maintained base box
  config.vm.box_url = "https://dl.dropbox.com/u/7225008/Vagrant/CentOS-6.3-x86_64-minimal.box"
  config.vm.box = "centos-6.3.box"

  
  # SSH - Forward 22 to 2222
  config.vm.forward_port 22, 2223
  # XRDP - Forward 3389 to 33389
  config.vm.forward_port 3389, 33389
  
  # Apply cookbooks
  config.vm.provision :chef_solo do |chef|
	chef.cookbooks_path = "cookbooks"
	chef.add_recipe("yum")
	end 
end