# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant::Config.run do |config|
  ### Troubleshooting Options ###
  
  # Enable for console access in Virtualbox
  #config.vm.boot_mode = :gui
  
  ### Main ###    
  # Setup the box - using a publicly maintained base box
  config.vm.box_url = "https://1412126a-vagrant.s3.amazonaws.com/CentOS-6.3-x86_64-reallyminimal.box"
  config.vm.box = "centos-6.3.box"
  
  # Setup a shared folder
  config.vm.share_folder "projects", "/projects", "c:\\projects", :create => true
  
  # SSH - Forward 22 to 2223
  config.vm.forward_port 22, 2223
  
  # Apply cookbooks
  config.vm.provision :chef_solo do |chef|
	chef.cookbooks_path = "cookbooks"
	chef.add_recipe("boilerplate::yum_update")
	end 
end